### PR TITLE
Add unit tests for Android Support

### PR DESCRIPTION
**Pull request by kageiit**
- Added unit tests around the cobertura plugin and extension.
- Added flavor support in android projects

### CODE REVIEW

**Comment by kageiit** [comment]
@stevesaliman Can we get this merged before cutting 2.3.0 final release?
The unit tests caught a bug in android support which was fixed in this PR

**Comment by kageiit** [comment]
@stevesaliman any chance you can take a look at this? :)

**Comment by stevesaliman** [comment]
I apologize for the delay.  I was hoping to address the plugin application order problem before releasing 2.3.0.  

I think the solution is to create an empty extension object, then have each task assume its own defaults at execution time for values that are null in the extension object, but that change is a bit more than I can squeeze into my free time at the moment.

I'm looking into merging this pull request now, but I have a quick question...  What is the ```DummyPlugin``` and ```DummyExtension``` used for?  

Steve

**Comment by kageiit** [comment]
Sounds good.

The Dummy plugin/extension are used to create a mock version of the android plugin to be able to unit test the android project code path. They essentially crate the tasks/extensions that a normal android plugin application would do.

**Comment by stevesaliman** [comment]
If the extension/default changes cause breakage, I agree with you about the 3.0 release.  I think I can do it in a way that doesn't break or change anything for the end user.  If I succeed, I think a 2.4 release would make sense.

Thanks for the explanation of the dummy plugin/extension.  I agree that we don't want to require the Android sdk just to build the Cobertura plugin.

I'll merge the code, and with luck, have a production release by the end of the day.

**Pull request merged**
