### PR TITLE
DeprecationLogger moved to another package

### PR DESCRIPTION
**Pull request by haluzator**
changed import, solves #168

### CODE REVIEW

**Comment by kam1sh** [comment]
@stevesaliman Can you please review this PR? This small fix can be really useful in recent Gradle versions.

**Comment by stevesaliman** [comment]
My main concern with this PR is backwards compatibility.  If I change the import statement, it will break older Gradle clients.

But there might be another way.  In older versions of gradle, DeprecationLogger has no methods of its own, but extends SingleMessageLogger, which has the code we need.  In newer versions of Gradle, they swapped the two classes, moving the methods into DeprecationLogger, but having SingleMessageLogger extend it.  The important bit is that SimpleMessageLogger hasn't moved, so I don't have the backwards compatibility issue.

I've published version 3.0.1-SNAPSHOT to the Maven Snapshot repository.  You can use it by including `maven { url "http://oss.sonatype.org/content/repositories/snapshots" }` in your build.gradle file.  Give that a try, and if it fixes the problem, I'll do a production release in a week or so.

**Comment by ajpenner** [comment]
Was version 3.0.1 ever published to the main repository?

**Comment by jjmartin540** [comment]
@stevesaliman Can you cut an official release and push to maven central? There are a whole bunch of artifactory installs that can't pull the new version until you do and in the meantime gradle from 6.3, 6.4, 6.5 and 6.6+ are all broken which is the default when someone installs a fresh gradle config and tries to use your project.

**Pull request closed without merging**
