### PR TITLE
Gradle 5.+ support - Closes #156

### LINKED ISSUE #156: Gradle 5.1 compabitility issues
In gradle 5.1, `TaskContainer.java` is now decorated with CollectionCallbackActionDecorator -> https://github.com/gradle/gradle/commit/b40f10ac6e52ceeb8ab2b4a45acd8c72693a6ad7#diff-40a5a0b3f1d659c2d18f3684d17156a5

 
This commit also applies the change to plugins owned by Gradle that make use of `TaskReportContainer` (internal API).

 
The cobertura plugin requires a change in `CoberturaReportsImpl` to use the new `CollectionCallbackACtionDecorator` in https://github.com/stevesaliman/gradle-cobertura-plugin/blob/master/src/main/groovy/net/saliman/gradle/plugin/cobertura/CoberturaReportsImpl.java#L12

### PR DESCRIPTION
**Pull request by rpalcolea**
Hi @stevesaliman

This is a fix for #156.

This prevents Gradle 5.+ from deprecation warnings. More details here: https://github.com/gradle/gradle/pull/8076#issuecomment-449080020

### CODE REVIEW

**Comment by rpalcolea** [comment]
Hi, this is safe for gradle 4

**Comment by rpalcolea** [comment]
Also updated to use 5.1 final @stevesaliman

**Comment by rpalcolea** [comment]
any chance we can get a release with this soon?

**Comment by stevesaliman** [comment]
I hope to be able to get a release out this weekend.  There are a couple of things that will need to be fixed first.

1. The testclient is still using Gradle 5.0.  It's gradle wrapper should probably be bumped to 5.1
2. The `assertExecuted`, `assertSkipped`, and `assertUpToDate` methods don't work the same way as they used to.  They no longer fail the test when the given task isn't executed, skipped, or up to date, respectively.  This is mostly because there is no longer ant `assert` statement in them, but also because they don't always handle invalid tasks.  For example, if an invalid task is given to `assertExecuted`, it won't fail because the task name won't appear in the output.  If an invalid task is given to `assertSkipped` it won't fail either because there is no 

I should be able to work on this over the weekend.

**Comment by rpalcolea** [comment]
Hi @stevesaliman,

Thanks for the feedback. I added the `assertTrue` back and also upgraded the testclient to 5.1 -> https://github.com/stevesaliman/gradle-cobertura-plugin/pull/158/commits/f4a0aea6096ac1b7eb978ce2117c6dfb8a12e7b2

**Comment by stevesaliman** [comment]
Thanks for the fix.  I still need to take a look at assertExecuted - I don't think will fail tests if the task doesn't show up at all in the output.

Also, Gradle 5.1 seems to have broken the signing plugin - or at least the plugin's usage of it.  I'll need to track that down as well.

**Comment by stevesaliman** [comment]
I think I've got the publishing bits figured out.  I'll finish testing it after the merge...

**Pull request merged**
